import type { Metadata } from "next";
import { Antonio, League_Spartan } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { promises as fs } from "fs";

const antonio = Antonio({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-antonio",
});

const spartan = League_Spartan({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-spartan",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type Planet = {
  name: string;
  overview: {
    content: string;
    source: string;
  };
  structure: {
    content: string;
    source: string;
  };
  geology: {
    content: string;
    source: string;
  };
  rotation: string;
  revolution: string;
  radius: string;
  temperature: string;
  images: {
    planet: string;
    internal: string;
    geology: string;
  };
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const file = await fs.readFile(process.cwd() + "/app/data/data.json", "utf8");
  const data: Planet[] = JSON.parse(file);

  return (
    <html lang="en">
      <body
        className={`${antonio.variable} ${spartan.variable} antialiased bg-stars bg-black-100 bg-cover bg-no-repeat`}
      >
        <Navbar data={data} />
        <main className="tablet:border-t-2 border-t-dark-gray relative">
          {children}
        </main>
      </body>
    </html>
  );
}
