import type { Metadata } from "next";
import { Antonio, League_Spartan } from "next/font/google";
import "./globals.css";

const antonio = Antonio({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-antonio",
});

const spartan = League_Spartan({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-spartan",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${antonio.variable} ${spartan.variable} antialiased bg-stars bg-black-100 bg-cover bg-no-repeat`}
      >
        {children}
      </body>
    </html>
  );
}
